return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.18.2",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 96,
  height = 64,
  tilewidth = 32,
  tileheight = 32,
  nextobjectid = 392,
  backgroundcolor = { 227, 227, 227 },
  properties = {
    ["background"] = "2.jpg",
    ["solidcolor"] = "#ff56b4f7"
  },
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      name = "Zones",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 368,
          name = "",
          type = "trigger",
          shape = "polygon",
          x = 888,
          y = 920,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 112, y = 16 },
            { x = 176, y = -40 },
            { x = 56, y = -56 }
          },
          properties = {
            ["targetId"] = 369
          }
        },
        {
          id = 369,
          name = "",
          type = "green",
          shape = "polygon",
          x = 1216,
          y = 888,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = -80 },
            { x = 144, y = -32 },
            { x = 72, y = 48 }
          },
          properties = {}
        },
        {
          id = 370,
          name = "",
          type = "trigger",
          shape = "polygon",
          x = 1576,
          y = 936,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = -24 },
            { x = 32, y = -64 },
            { x = 56, y = -16 }
          },
          properties = {
            ["targetId"] = 371
          }
        },
        {
          id = 371,
          name = "",
          type = "blue",
          shape = "polygon",
          x = 1816,
          y = 808,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 104, y = 72 },
            { x = 208, y = 88 },
            { x = 360, y = 32 },
            { x = 168, y = 0 }
          },
          properties = {}
        },
        {
          id = 373,
          name = "",
          type = "yellow",
          shape = "polygon",
          x = 2344,
          y = 896,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 104 },
            { x = 104, y = 112 },
            { x = 128, y = 16 }
          },
          properties = {}
        },
        {
          id = 374,
          name = "",
          type = "green",
          shape = "polygon",
          x = 672,
          y = 1056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -56, y = 192 },
            { x = 24, y = 144 }
          },
          properties = {}
        },
        {
          id = 375,
          name = "switch",
          type = "trigger",
          shape = "polygon",
          x = 904,
          y = 1232,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 104, y = 112 },
            { x = 200, y = 32 },
            { x = 112, y = 0 }
          },
          properties = {
            ["targetId"] = 376
          }
        },
        {
          id = 376,
          name = "",
          type = "blue",
          shape = "polygon",
          x = 1256,
          y = 1224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 88, y = -56 },
            { x = 232, y = 32 },
            { x = 128, y = 72 }
          },
          properties = {}
        },
        {
          id = 377,
          name = "",
          type = "red",
          shape = "polygon",
          x = 1656,
          y = 1240,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 96 },
            { x = 104, y = 160 },
            { x = 152, y = 128 }
          },
          properties = {}
        },
        {
          id = 378,
          name = "switch",
          type = "trigger",
          shape = "polygon",
          x = 2008,
          y = 1264,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 152, y = -56 },
            { x = 288, y = -24 },
            { x = 168, y = 24 }
          },
          properties = {
            ["targetId"] = 377
          }
        },
        {
          id = 379,
          name = "body",
          type = "green",
          shape = "ellipse",
          x = 1472,
          y = 808,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 380,
          name = "body",
          type = "blue",
          shape = "ellipse",
          x = 2000,
          y = 1400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 381,
          name = "body",
          type = "red",
          shape = "ellipse",
          x = 1296,
          y = 1376,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 382,
          name = "body",
          type = "blue",
          shape = "ellipse",
          x = 2240,
          y = 904,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 383,
          name = "body",
          type = "blue",
          shape = "ellipse",
          x = 752,
          y = 1048,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 384,
          name = "body",
          type = "yellow",
          shape = "rectangle",
          x = 1488,
          y = 1376,
          width = 64,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 385,
          name = "body",
          type = "red",
          shape = "rectangle",
          x = 1616,
          y = 720,
          width = 56,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 386,
          name = "body",
          type = "red",
          shape = "rectangle",
          x = 2360,
          y = 1112,
          width = 72,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 387,
          name = "body",
          type = "yellow",
          shape = "rectangle",
          x = 672,
          y = 792,
          width = 64,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 388,
          name = "body",
          type = "yellow",
          shape = "ellipse",
          x = 1720,
          y = 864,
          width = 56,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 389,
          name = "body",
          type = "red",
          shape = "ellipse",
          x = 1080,
          y = 704,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 390,
          name = "body",
          type = "green",
          shape = "ellipse",
          x = 1088,
          y = 1400,
          width = 56,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 391,
          name = "body",
          type = "green",
          shape = "ellipse",
          x = 1784,
          y = 1192,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "Triggers",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      name = "Solid",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 318,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 976,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 319,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 976,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 320,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 1040,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 321,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 1072,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 322,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 1104,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 323,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 976,
          width = 32,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 324,
          name = "",
          type = "",
          shape = "rectangle",
          x = 976,
          y = 1104,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 326,
          name = "",
          type = "",
          shape = "rectangle",
          x = 976,
          y = 1040,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 327,
          name = "",
          type = "",
          shape = "rectangle",
          x = 976,
          y = 976,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 328,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1072,
          y = 976,
          width = 32,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 329,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1104,
          y = 1104,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 330,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1104,
          y = 1040,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 331,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1104,
          y = 976,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 332,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1232,
          y = 976,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 333,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1264,
          y = 1040,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 334,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1296,
          y = 976,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 336,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1296,
          y = 1072,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 337,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1232,
          y = 1104,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 338,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1360,
          y = 976,
          width = 32,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 339,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1392,
          y = 976,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 340,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1424,
          y = 1008,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 341,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1392,
          y = 1104,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 342,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1488,
          y = 976,
          width = 32,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 344,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1520,
          y = 1104,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 345,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1552,
          y = 976,
          width = 32,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 346,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1648,
          y = 976,
          width = 32,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 347,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1680,
          y = 1104,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 348,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1776,
          y = 976,
          width = 32,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 349,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1808,
          y = 976,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 350,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1840,
          y = 1008,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 351,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1808,
          y = 1040,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 352,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1936,
          y = 1008,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 353,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1904,
          y = 976,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 355,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2032,
          y = 976,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 356,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2032,
          y = 1016,
          width = 32,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 357,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2064,
          y = 1104,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 359,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2032,
          y = 1008,
          width = 32,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 360,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2064,
          y = 1040,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 361,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2160,
          y = 976,
          width = 32,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 362,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2192,
          y = 976,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 363,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2224,
          y = 1008,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 365,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2192,
          y = 1040,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 367,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2224,
          y = 1072,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "Entities",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 305,
          name = "player",
          type = "red",
          shape = "ellipse",
          x = 808,
          y = 1312,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
